name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "REACT_APP_API_URL=http://localhost:8000" >> frontend/.env

      - name: Build and start Docker containers
        run: |
          docker compose up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          RETRIES=10
          COUNT=0
          until curl -sSf http://localhost:8000/healthcheck > /dev/null; do
            echo "Backend is unavailable - retrying... ($COUNT/$RETRIES)"
            COUNT=$((COUNT+1))
            if [ "$COUNT" -ge "$RETRIES" ]; then
              echo "Backend did not become ready in time. Exiting..."
              exit 1
            fi
            sleep 2
          done
          echo "Backend is ready!"

      - name: Install dependencies
        run: |
          docker compose exec -T frontend npm install

      - name: Run ESLint (Code Linting)
        run: |
          docker compose exec -T frontend npm run lint

      - name: Run Jest tests
        run: |
          docker compose exec -T frontend npm test -- --coverage --watchAll=false

      - name: Stop Docker containers
        run: |
          docker compose down